services:
  backend:
    build:
      context: ./backend  # Path to your FastAPI backend Dockerfile
    container_name: backend
    ports:
      - "8000:8000"  # Expose FastAPI on port 8000
    environment:
      - FASTAPI_ENV=production
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "https://pueedtoh01.execute-api.us-east-2.amazonaws.com/prod/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend  # Path to your frontend Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    container_name: frontend
    ports:
      - "3000:3000"  # Expose frontend (Node.js server or static server)
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
