export const initialRowState = Array.from({ length: 10 }, () => ({
    card_name: '',
    card_id: '',
    foil: false,
    non_foil: false,
    surgefoil: false,
    etched: false,
    extended_art: false,
    full_art: false,
    reverse_holo: false,
    first_edition: false,
    card_count: 1,
    variant: true,
    variant_type: '',
    source_image: '',
    card_name_id_invalid: false,
    non_foil_invalid: false,
    foil_invalid: false,
    surgefoil_invalid: false,
    etched_invalid: false,
    extended_art_invalid: false,
    full_art_invalid: false,
    reverse_holo_invalid: false,
    first_edition_invalid: false,
    card_count_invalid: false,
    isInvalid: false,
}));